### ISSUE TITLE
Is this project really deprecated? 

### ISSUE THREAD

**Issue by Serkan-devel** [maidsafe/MaidSafe-DHT#27]
The Readme links to another deprecated project and this one seems more recent

**Comment by Fraser999** [comment]
Yes, this is deprecated.  We have moved [our codebase](https://github.com/maidsafe?utf8=%E2%9C%93&q=&type=public&language=rust) over to Rust.

**Comment by Serkan-devel** [comment]
Is this repository https://github.com/maidsafe/routing the continuation of this project?

**Comment by Fraser999** [comment]
Yes, that's correct.  Apologies - I should have just linked to that in my previous comment!
